language: csharp
sudo: false
before_install: npm install -g grunt-cli
install: curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | sh && source ~/.dnx/dnvm/dnvm.sh && dnvm upgrade && npm install
script: grunt unit-test
