install:
    - sudo apt-get update
    - sudo apt-get install -y unzip curl
    - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
    - sudo apt-get install -y libunwind8
    - dnvm upgrade -r coreclr
    - npm install
script:
    - source dnxpath.sh
    - source dnupath.sh
    - grunt build
    - grunt test
