language: nodejs

before_install:
    - npm install -g grunt-cli
    - sudo apt-get -qq update
    - sudo echo "deb http://de.archive.ubuntu.com/ubuntu trusty main" >> /etc/apt/sources.list
    - sudo apt-get install -y libunwind8
install:
    - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | sh
    - source ~/.dnx/dnvm/dnvm.sh
    - dnvm install -r $DNX_RUNTIME -arch $DNX_ARCH $DNX_VERSION
    - dnvm use -r $DNX_RUNTIME -arch $DNX_ARCH $DNX_VERSION
    - wget -q https://releases.hashicorp.com/consul/0.6.3/consul_0.6.3_linux_amd64.zip
    - unzip -qq consul_0.6.3_linux_amd64.zip -d consul
    - sudo mv consul/consul /usr/bin
    - npm install
script:
    - grunt build
    - grunt unit-test
    - mv
#deploy:
#    on:
#        tags: true
